trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12.1'
    addToPath: true

- script: |
    python -m venv .healthai
    source env/bin/activate
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    zip -r app.zip .
  displayName: 'Archive application files'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '<Your Azure Subscription>'
    appName: '<Your App Service Name>'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
  displayName: 'Deploy to Azure Web App'
